INFO 2025-03-28 23:13:14,712 Watching for file changes with StatReloader
WARNING 2025-03-28 23:13:17,198 Bad Request: /projects/add/
WARNING 2025-03-28 23:13:17,198 "POST /projects/add/ HTTP/1.1" 400 164
INFO 2025-03-28 23:13:33,382 "GET /clientdata/client/3 HTTP/1.1" 200 34434
WARNING 2025-03-28 23:13:48,934 Bad Request: /projects/add/
WARNING 2025-03-28 23:13:48,935 "POST /projects/add/ HTTP/1.1" 400 164
INFO 2025-03-28 23:25:30,474 "GET /projects/ HTTP/1.1" 200 26783
INFO 2025-03-28 23:44:37,359 "GET /clientdata/clients/ HTTP/1.1" 200 22316
INFO 2025-03-28 23:44:41,168 "GET /clientdata/client/4 HTTP/1.1" 200 31824
INFO 2025-03-28 23:45:23,243 "POST /clientdata/cars/add_car/ HTTP/1.1" 200 30
INFO 2025-03-28 23:45:25,002 "GET /clientdata/client/4 HTTP/1.1" 200 33405
WARNING 2025-03-28 23:45:49,239 Bad Request: /projects/add/
WARNING 2025-03-28 23:45:49,240 "POST /projects/add/ HTTP/1.1" 400 164
WARNING 2025-03-28 23:46:00,066 Bad Request: /projects/add/
WARNING 2025-03-28 23:46:00,066 "POST /projects/add/ HTTP/1.1" 400 246
WARNING 2025-03-28 23:46:13,352 Bad Request: /projects/add/
WARNING 2025-03-28 23:46:13,352 "POST /projects/add/ HTTP/1.1" 400 164
INFO 2025-03-28 23:48:20,390 D:\Developments\topcauchos_end\core\projects\models.py changed, reloading.
INFO 2025-03-28 23:48:21,288 Watching for file changes with StatReloader
INFO 2025-03-28 23:49:28,716 D:\Developments\topcauchos_end\core\projects\models.py changed, reloading.
INFO 2025-03-28 23:49:29,338 Watching for file changes with StatReloader
INFO 2025-03-28 23:49:34,767 D:\Developments\topcauchos_end\core\projects\models.py changed, reloading.
INFO 2025-03-28 23:49:35,393 Watching for file changes with StatReloader
INFO 2025-03-28 23:49:44,456 "GET /clientdata/client/4 HTTP/1.1" 302 0
INFO 2025-03-28 23:49:44,479 "GET /login/?next=/clientdata/client/4 HTTP/1.1" 200 4095
WARNING 2025-03-28 23:49:44,831 "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
WARNING 2025-03-28 23:49:44,832 "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
INFO 2025-03-28 23:49:52,521 "POST /login/ HTTP/1.1" 302 0
INFO 2025-03-28 23:49:52,549 "GET / HTTP/1.1" 200 14942
INFO 2025-03-28 23:49:55,111 "GET /clientdata/clients/ HTTP/1.1" 200 22316
INFO 2025-03-28 23:49:57,129 "GET /clientdata/client/4 HTTP/1.1" 200 33222
WARNING 2025-03-28 23:50:10,731 Bad Request: /projects/add/
WARNING 2025-03-28 23:50:10,731 "POST /projects/add/ HTTP/1.1" 400 164
INFO 2025-03-28 23:50:46,444 Watching for file changes with StatReloader
WARNING 2025-03-28 23:50:48,463 Bad Request: /projects/add/
WARNING 2025-03-28 23:50:48,463 "POST /projects/add/ HTTP/1.1" 400 164
INFO 2025-03-28 23:57:03,030 Watching for file changes with StatReloader
INFO 2025-03-28 23:57:06,750 "GET /clientdata/client/4 HTTP/1.1" 200 33594
ERROR 2025-03-28 23:57:20,702 Internal Server Error: /projects/add/
Traceback (most recent call last):
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Developments\topcauchos_end\.venv\Lib\site-packages\django\views\generic\edit.py", line 149, in post
    form = self.get_form()
  File "D:\Developments\topcauchos_end\core\projects\views.py", line 102, in get_form
    form.fields['car'].queryset = Car.objects.none()
                                  ^^^
UnboundLocalError: cannot access local variable 'Car' where it is not associated with a value
ERROR 2025-03-28 23:57:20,705 "POST /projects/add/ HTTP/1.1" 500 96239
INFO 2025-03-28 23:59:35,735 D:\Developments\topcauchos_end\core\projects\views.py changed, reloading.
INFO 2025-03-28 23:59:36,371 Watching for file changes with StatReloader
INFO 2025-03-28 23:59:39,609 D:\Developments\topcauchos_end\core\projects\views.py changed, reloading.
INFO 2025-03-28 23:59:40,207 Watching for file changes with StatReloader
